//
//  SummaryCard.swift
//  CampusDAO
//
//  Created by CHETHAN R on 11/15/25.
//

import SwiftUI

struct SummaryCard: View {
    var summary: String

    var body: some View {
        VStack(alignment: .leading, spacing: 12) {

            HStack {
                Image(systemName: "brain.head.profile")
                    .foregroundColor(.purple)
                    .font(.title2)

                Text("AI Summary")
                    .font(Theme.Fonts.headline)
            }

            Text(summary)
                .font(Theme.Fonts.body)
                .foregroundColor(Theme.Colors.textSecondary)

            Divider()

            Text("Generated by CampusDAO AI")
                .font(Theme.Fonts.small)
                .foregroundColor(.secondary)

        }
        .padding(Theme.Padding.card)
        .background(Theme.Colors.cardBackground)
        .cornerRadius(Theme.Radius.medium)
        .shadow(color: Theme.Shadow.light, radius: 5, x: 0, y: 3)
    }
}
